### ISSUE TITLE
Add RSS feed for Blog

### ISSUE THREAD

**Issue by puresick** [usebruno/bruno-website#4]
Hi :wave:.

I just found out about [Bruno on Hacker News](https://news.ycombinator.com/item?id=37701803) and love the idea of [your principals](https://github.com/usebruno/bruno/discussions/269)! Always a joy to see projects aiming for sustainability and privacy instead of joining others into their short-sighted approach.

I'd like to keep up to date with the projects progress and tried to subscribe to the blog via my RSS reader. Sadly, it does not offer a RSS feed.

Would that be something viable to add to your blog?

**Comment by santhosh-chinnasamy** [comment]
I'll be working on it.
